apiVersion: v1
kind: ConfigMap
metadata:
  name: video-conference-config
  namespace: video-conference
data:
  # 数据库配置
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "video_conference"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  
  # 服务端口配置
  USER_SERVICE_PORT: "8081"
  MEETING_SERVICE_PORT: "8082"
  SIGNALING_SERVICE_PORT: "8083"
  MEDIA_SERVICE_PORT: "8084"
  DETECTION_SERVICE_PORT: "8085"
  RECORD_SERVICE_PORT: "8086"
  NOTIFICATION_SERVICE_PORT: "8087"
  GATEWAY_SERVICE_PORT: "8080"
  AI_DETECTION_PORT: "8501"
  
  # 应用配置
  LOG_LEVEL: "INFO"
  JWT_EXPIRY: "24h"
  MAX_MEETING_PARTICIPANTS: "50"
  MEDIA_STORAGE_PATH: "/app/storage/media"
  DETECTION_STORAGE_PATH: "/app/storage/detection"
  
  # WebRTC配置
  STUN_SERVERS: "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302"
  TURN_SERVERS: ""
  
  # AI检测配置
  AI_DETECTION_ENABLED: "true"
  DETECTION_THRESHOLD: "0.8"
  DETECTION_MODELS_PATH: "/app/models"
