global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@meeting-system.com'
  smtp_auth_username: 'alertmanager@meeting-system.com'
  smtp_auth_password: 'your-password-here'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree
route:
  receiver: 'default'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Error alerts
    - match:
        severity: error
      receiver: 'error-alerts'
      repeat_interval: 15m
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 1h

# Receivers
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/webhook/critical'
        send_resolved: true
    # Email notification (uncomment and configure)
    # email_configs:
    #   - to: 'ops-team@meeting-system.com'
    #     headers:
    #       Subject: '[CRITICAL] {{ .GroupLabels.alertname }}'

  - name: 'error-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/webhook/error'
        send_resolved: true

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/webhook/warning'
        send_resolved: true

# Inhibition rules
inhibit_rules:
  # Inhibit warning if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
  
  # Inhibit error if critical alert is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'error'
    equal: ['alertname', 'service']

