# 用户服务配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"
  read_timeout: 60
  write_timeout: 60

# gRPC配置
grpc:
  port: 50051

# PostgreSQL数据库配置
database:
  host: "localhost"
  port: 15432
  user: "postgres"
  password: "password"
  dbname: "meeting_system"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# Redis配置
redis:
  host: "localhost"
  port: 16379
  password: ""
  db: 0
  pool_size: 10

# JWT配置
jwt:
  secret: "meeting-system-secret-key-change-in-production"
  expire_time: 24

# 日志配置
log:
  level: "info"
  filename: "logs/user-service.log"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: true

etcd:
  endpoints:
    - "localhost:2379"
  dial_timeout: 5
  ttl: 30
  namespace: "/services"

# 消息队列配置
message_queue:
  enabled: true
  type: "redis"
  queue_name: "meeting_system"
  workers: 4
  visibility_timeout: 30
  poll_interval: 100
  max_retries: 3
  enable_dead_letter_queue: true

# 任务调度器配置
task_scheduler:
  enabled: true
  workers: 2
  buffer_size: 100

# 事件总线配置
event_bus:
  enabled: true
  type: "redis_pubsub"
  buffer_size: 100
  workers: 2
