#!/usr/bin/env bash
set -euo pipefail

# Generate a local (gitignored) upstream server list for ai_inference_service.
#
# Usage:
#   AI_INFERENCE_UPSTREAMS="gpu1.example.com:51312 gpu2.example.com:51306" \
#   ./meeting-system/nginx/scripts/gen_ai_inference_service_servers_conf.sh
#
# Or from file:
#   AI_INFERENCE_UPSTREAMS_FILE=./nodes.public.txt \
#   ./meeting-system/nginx/scripts/gen_ai_inference_service_servers_conf.sh
#
# Output:
#   meeting-system/nginx/conf.d/ai_inference_service.servers.local.conf

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
NGINX_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

AI_INFERENCE_UPSTREAMS="${AI_INFERENCE_UPSTREAMS:-}"
AI_INFERENCE_UPSTREAMS_FILE="${AI_INFERENCE_UPSTREAMS_FILE:-}"
AI_INFERENCE_SERVERS_CONF_OUT="${AI_INFERENCE_SERVERS_CONF_OUT:-${NGINX_DIR}/conf.d/ai_inference_service.servers.local.conf}"

AI_INFERENCE_MAX_FAILS="${AI_INFERENCE_MAX_FAILS:-3}"
AI_INFERENCE_FAIL_TIMEOUT="${AI_INFERENCE_FAIL_TIMEOUT:-30s}"

endpoints=()

if [[ -n "${AI_INFERENCE_UPSTREAMS_FILE}" ]]; then
  if [[ ! -f "${AI_INFERENCE_UPSTREAMS_FILE}" ]]; then
    echo "AI_INFERENCE_UPSTREAMS_FILE not found: ${AI_INFERENCE_UPSTREAMS_FILE}" >&2
    exit 1
  fi
  while IFS= read -r line; do
    line="${line%%#*}"
    line="$(echo "${line}" | xargs)"
    [[ -z "${line}" ]] && continue
    endpoints+=("${line}")
  done < "${AI_INFERENCE_UPSTREAMS_FILE}"
else
  raw="${AI_INFERENCE_UPSTREAMS//,/ }"
  read -r -a endpoints <<< "${raw}"
fi

if [[ "${#endpoints[@]}" -eq 0 ]]; then
  cat >&2 <<'EOF'
No upstreams provided.

Provide either:
  - AI_INFERENCE_UPSTREAMS="host1:port host2:port"
  - AI_INFERENCE_UPSTREAMS_FILE=/path/to/list.txt   (one host:port per line)
EOF
  exit 1
fi

for ep in "${endpoints[@]}"; do
  if [[ "${ep}" != *:* ]]; then
    echo "Invalid upstream (expected host:port): ${ep}" >&2
    exit 1
  fi
  host="${ep%:*}"
  port="${ep##*:}"
  if [[ -z "${host}" || -z "${port}" || ! "${port}" =~ ^[0-9]+$ ]]; then
    echo "Invalid upstream (expected host:port): ${ep}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname -- "${AI_INFERENCE_SERVERS_CONF_OUT}")"

tmp="$(mktemp)"
{
  echo "# Generated by $(basename "$0") at $(date -u +%FT%TZ)"
  echo "# This file is gitignored. Do NOT commit real infrastructure endpoints."
  echo
  for ep in "${endpoints[@]}"; do
    echo "server ${ep} max_fails=${AI_INFERENCE_MAX_FAILS} fail_timeout=${AI_INFERENCE_FAIL_TIMEOUT};"
  done
} > "${tmp}"

chmod 0644 "${tmp}"
mv "${tmp}" "${AI_INFERENCE_SERVERS_CONF_OUT}"

echo "Wrote: ${AI_INFERENCE_SERVERS_CONF_OUT}"
