apiVersion: v1
kind: Service
metadata:
  name: ai-detection-service
  namespace: video-conference
  labels:
    app: ai-detection-service
spec:
  ports:
    - port: 8501
      targetPort: 8501
      name: http
  selector:
    app: ai-detection-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-detection-service
  namespace: video-conference
  labels:
    app: ai-detection-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-detection-service
  template:
    metadata:
      labels:
        app: ai-detection-service
    spec:
      containers:
      - name: ai-detection-service
        image: video-conference/ai-detection-service:latest
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: video-conference-config
              key: AI_DETECTION_PORT
        - name: MODELS_PATH
          valueFrom:
            configMapKeyRef:
              name: video-conference-config
              key: DETECTION_MODELS_PATH
        envFrom:
        - configMapRef:
            name: video-conference-config
        - secretRef:
            name: video-conference-secrets
        volumeMounts:
        - name: ai-models-storage
          mountPath: /app/models
        - name: detection-storage
          mountPath: /app/storage/detection
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        imagePullPolicy: Always
      volumes:
      - name: ai-models-storage
        persistentVolumeClaim:
          claimName: ai-models-pvc
      - name: detection-storage
        persistentVolumeClaim:
          claimName: detection-storage-pvc
      restartPolicy: Always
