apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: video-conference
  labels:
    app: gateway-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: gateway-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: video-conference
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: video-conference/gateway-service:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: video-conference-config
              key: GATEWAY_SERVICE_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: video-conference-secrets
              key: JWT_SECRET
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: video-conference-config
              key: LOG_LEVEL
        envFrom:
        - configMapRef:
            name: video-conference-config
        - secretRef:
            name: video-conference-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
      restartPolicy: Always
