apiVersion: v1
kind: Service
metadata:
  name: meeting-service
  namespace: video-conference
  labels:
    app: meeting-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  selector:
    app: meeting-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-service
  namespace: video-conference
  labels:
    app: meeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-service
  template:
    metadata:
      labels:
        app: meeting-service
    spec:
      containers:
      - name: meeting-service
        image: video-conference/meeting-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: video-conference-config
              key: MEETING_SERVICE_PORT
        envFrom:
        - configMapRef:
            name: video-conference-config
        - secretRef:
            name: video-conference-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
      restartPolicy: Always
