apiVersion: v1
kind: Service
metadata:
  name: web-client-service
  namespace: video-conference
  labels:
    app: web-client
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: web-client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: video-conference
  labels:
    app: web-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: web-client-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: web-client-content
        configMap:
          name: web-client-content
      - name: nginx-config
        configMap:
          name: nginx-config
      restartPolicy: Always
