apiVersion: v1
kind: Secret
metadata:
  name: video-conference-secrets
  namespace: video-conference
type: Opaque
data:
  # 数据库密码 (base64编码)
  POSTGRES_USER: YWRtaW4=  # admin
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  MONGODB_USER: YWRtaW4=  # admin
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  RABBITMQ_USER: YWRtaW4=  # admin
  RABBITMQ_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  
  # JWT密钥
  JWT_SECRET: dmlkZW8tY29uZmVyZW5jZS1qd3Qtc2VjcmV0LWtleS0yMDI0  # video-conference-jwt-secret-key-2024
  
  # 加密密钥
  ENCRYPTION_KEY: YWVzLTI1Ni1lbmNyeXB0aW9uLWtleS0yMDI0  # aes-256-encryption-key-2024
  
  # 外部服务API密钥
  SMTP_PASSWORD: ""  # 邮件服务密码
  SMS_API_KEY: ""    # 短信服务API密钥
  
  # 对象存储密钥
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
